services:
  api:
    build: ./images/api
    ports:
      - 3000:3000
    volumes:
      - ./images/api/src:/usr/app/src
    environment:
      NODE_ENV: development
    env_file:
      - ./images/config/.env.development
    depends_on:
      store:
        condition: service_healthy
    command: ["npm", "run", "dev"]

  store:
    image: mysql:latest
    restart: on-failure
    ports:
      - 3306:3306
    volumes:
      - ./_dev_mysql_data:/var/lib/mysql/data
    env_file:
      - ./images/config/.env.development
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
